name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ["v*"]

env:
  PKG_NAME: quicknxs

jobs:
  conda-verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify conda package
        uses: ./
        with:
          # local-channel: /tmp/local-channel
          package-name: ${{ env.PKG_NAME }}
          # module-name: ${{ env.PKG_NAME }}
          extra-channels: neutrons mantid
          extra-commands: |
            echo "This is a test of a multiline"
            output=$(date)
            echo "${output}"
